namespace KafeYana.Infrastructure.Servicios.FacturacionImpresion
{
    /// <summary>
    /// Logo de KAFE YANA como bitmap monocromo 1-bit (72x97 px) para el
    /// encabezado del ticket. Rasterizado una sola vez desde
    /// <c>frontend/src/assets/img/logo.svg</c>; formato: 4 bytes de cabecera
    /// (ancho y alto, uint16 little-endian) + filas empaquetadas MSB-first
    /// (bit 1 = punto negro).
    /// </summary>
    internal static class FacturaLogo
    {
        private const string BlobBase64 =
            "SABhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAQAAAAAAAAAAAwAAAAAAAAAABwAAAAAAAAAABwAAAAAAAAAAB4AAAAAAAAAAB4AAAAAAAAAAB8AAAAAAAAAAA+AAAAAAAAAAA+AAAAAAAAAAGfAAAAAAAAAAGPgAAAAAAAAAHHgAAAAAAAAADHgAAAAAAAAADHmAAAAAAAAAHHmAAAAAAAAAHHmAAAAAAAAAPPnAAAAAAAAAPPHAAAAAAAAAefOAAAAAAAAAeeeAAAAAAAAA8+cAAAAAAAAA988AAAAAAAAB594AAAAAAAAB55wAAAAAAAAB57wAAAAAAAAB57gAAAAAAAAA97gAAAAAAAAA97gAAAAAAAAAd5gAAAAAAAAAe9gAAAAAAAAAO8gAAAAAAAAAG8AAAAAAAAAADcAAAAAAAAAD6ceAAAAAAAAfwcPgAAAAAAB8A8B4AAAAAADwA4A8AAAAAAHABwAcAAAAAAPADgA8AAAAAAPACAA8AAAAAAPgAAD48AAAAAH8AAfz/AAAAAD////n/gAAAAA///+P/gAAAAIP//4OHwAAAAMA/8AMDwAAAAMAAAAcDwAAAAMAAAAYDwAAAAMAAAAAHgAAAAMAAAAAPgAAAAMAAAAAfAAAAAOAAAAA+AAAAAOAAAAB8AAAAAOAAAAD4AAAAAOAAAAHwAAAAAHAAAAPAAAAAAHAAAAOAAAAAAHAAAAcAAAAAAHgAAAcAAAAAADgAAAYAAAAAADwAAAYAAAAAAB4AAAYAAAAAAB8AAAQAAAAABA/AACAAAAAABgfwAeAAAAAABgP//8AAAAAABgD//wAAAAAABwA//AAAAAAAA8AAAAAAAAAAA+AAAD/4AAAAAfwAD//+AAAAAH//////gAAAAD////AAAAAAAAf//gAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

        private static readonly byte[] Blob = Convert.FromBase64String(BlobBase64);

        public static int Ancho => Blob[0] | (Blob[1] << 8);
        public static int Alto => Blob[2] | (Blob[3] << 8);

        /// <summary>Bitmap sin la cabecera de 4 bytes.</summary>
        public static byte[] Bits => Blob[4..];

        public static void Escribir(MemoryStream ms) =>
            FacturaEscPosRaster.Escribir(ms, Bits, Ancho, Alto);
    }
}
