using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KafeYana.Infrastructure.Migrations
{
    /// <summary>
    /// Arregla la tabla "Detalle_Pago" agregando la numeración automática (IDENTITY) a la columna "Id".
    ///
    /// Causa: la tabla fue creada con un script SQL manual en Azure que omitió
    ///        "GENERATED BY DEFAULT AS IDENTITY" (o "SERIAL"). El modelo EF Core
    ///        sí la declara como identity, pero EF al hacer INSERT enviaba "Id = 0"
    ///        chocando con "PK_Detalle_Pago" en cuanto la tabla tenía ≥1 fila.
    ///
    /// Síntoma original: ventas concurrentes devolvían HTTP 409 con el mensaje
    ///                   genérico "Ya existe un registro con esos datos." porque
    ///                   "PK_Detalle_Pago" no estaba mapeado en ExceptionGlobal.ResolverUnico.
    ///
    /// Es idempotente: si la columna ya es identity en la BD, no hace nada.
    /// </summary>
    public partial class FixDetallePagoIdentitySequence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1) Crear la sequence si no existe.
            migrationBuilder.Sql(
                "CREATE SEQUENCE IF NOT EXISTS \"Detalle_Pago_Id_seq\";");

            // 2) Sincronizar la sequence con el MAX(Id) actual + 1 para que el próximo
            //    valor no choque con filas existentes.
            migrationBuilder.Sql(
                "DO $$ BEGIN " +
                "  IF NOT EXISTS (" +
                "    SELECT 1 FROM pg_attribute " +
                "    WHERE attrelid = '\"Detalle_Pago\"'::regclass AND attname = 'Id' AND attidentity <> ''" +
                "  ) THEN " +
                "    PERFORM setval(" +
                "      pg_get_serial_sequence('\"Detalle_Pago\"', 'Id')," +
                "      GREATEST(COALESCE((SELECT MAX(\"Id\") FROM \"Detalle_Pago\"), 0) + 1, 1)," +
                "      false" +
                "    );" +
                "  END IF; " +
                "END $$;");

            // 3) Hacer la columna Id identity (GENERATED BY DEFAULT AS IDENTITY).
            //    IF EXISTS evita error si ya es identity.
            migrationBuilder.Sql(
                "ALTER TABLE \"Detalle_Pago\" " +
                "ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            // 4) Atar la sequence que ya existía a la columna.
            migrationBuilder.Sql(
                "ALTER SEQUENCE \"Detalle_Pago_Id_seq\" OWNED BY \"Detalle_Pago\".\"Id\";");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Quita la propiedad identity. OJO: esto NO borra filas, sólo el autonumérico.
            // Si la tabla tiene datos, la columna seguirá permitiendo inserts con Id explícito.
            migrationBuilder.Sql(
                "ALTER TABLE \"Detalle_Pago\" " +
                "ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        }
    }
}
