// <auto-generated />
using System;
using KafeYana.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KafeYana.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424184938_FixDetalleRondaOpcionUniqueIndex")]
    partial class FixDetalleRondaOpcionUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KafeYana.Core.Entities.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refreshtoken", (string)null);
                });

            modelBuilder.Entity("KafeYana.Core.Entities.Entity.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("KafeYana.Core.Entities.Inventario.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correonormalizado")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Dni")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("Fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasFilter("\"Correo\" <> ''");

                    b.HasIndex("Correonormalizado")
                        .IsUnique()
                        .HasFilter("\"Correonormalizado\" <> ''");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasFilter("\"Dni\" IS NOT NULL");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Detalle_venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_venta")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_venta");

                    b.ToTable("Detalle_venta", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Ajuste", b =>
                {
                    b.Property<int>("Id_Insumo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Opcion")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Id_InsumoNuevo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAjuste")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_Insumo", "Id_Opcion");

                    b.HasIndex("Id_Insumo");

                    b.HasIndex("Id_InsumoNuevo");

                    b.HasIndex("Id_Opcion");

                    b.ToTable("Ajuste", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Comprado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo_barra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Costo_compra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Id_Producto")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Stock_actual")
                        .HasColumnType("integer");

                    b.Property<int>("Stock_minimo")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_barra");

                    b.HasIndex("Disponible");

                    b.HasIndex("Id_Producto")
                        .IsUnique();

                    b.ToTable("Comprado", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle", b =>
                {
                    b.Property<int>("Id_receta")
                        .HasColumnType("integer");

                    b.Property<int>("Id_insumo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Merma")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_receta", "Id_insumo");

                    b.HasIndex("Id_insumo");

                    b.ToTable("Detalle", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle_Ronda_Opcion", b =>
                {
                    b.Property<int>("Id_Detalle_Ronda")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Opcion")
                        .HasColumnType("integer");

                    b.HasKey("Id_Detalle_Ronda", "Id_Opcion");

                    b.HasIndex("Id_Opcion");

                    b.HasIndex("Id_Detalle_Ronda", "Id_Opcion")
                        .IsUnique()
                        .HasDatabaseName("ix_detalle_ronda_opcion_unique");

                    b.ToTable("Detalle_Ronda_Opcion", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle_ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Ronda")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre_Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Precio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Producto");

                    b.HasIndex("ProductoId");

                    b.HasIndex("Id_Ronda", "Id_Producto")
                        .IsUnique()
                        .HasDatabaseName("ix_detalle_ronda_ronda_producto_unique");

                    b.ToTable("Detalle_Ronda", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Elaborado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Producto")
                        .HasColumnType("integer");

                    b.Property<bool>("Producible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Stock_actual")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Producto")
                        .IsUnique();

                    b.ToTable("Elaborado", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Factor_conversion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Stock_actual")
                        .HasColumnType("integer");

                    b.Property<int>("Stock_min")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad_compra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unidad_min_uso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Insumo", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("Id_Pedido")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_Pedido")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AjustePrecio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Id_variacion")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Id_variacion");

                    b.ToTable("Opcion", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria_Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("id_nombre_producto");

                    b.HasIndex("Tipo");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Promocion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Producto_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Producto_Id")
                        .IsUnique();

                    b.ToTable("Promocion", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.PromocionDetalle", b =>
                {
                    b.Property<int>("Id_Producto")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Promocion")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<bool>("Opcional")
                        .HasColumnType("boolean");

                    b.HasKey("Id_Producto", "Id_Promocion");

                    b.HasIndex("Id_Promocion");

                    b.ToTable("Detalle_promocion", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Id_Elaborado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasDefaultValue("");

                    b.Property<int>("Porciones")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Elaborado")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Receta", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("integer");

                    b.Property<string>("Ronda_Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Pedido");

                    b.ToTable("Ronda", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Stock_Ajuste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ajuste")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Perdida")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stock_ajuste", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Variacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Elaborado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Requerido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Id_Elaborado");

                    b.HasIndex("Nombre");

                    b.HasIndex("Requerido");

                    b.ToTable("Variacion", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Id_Cliente")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Id_Cliente")
                        .IsUnique();

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("DNI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("Razon_Social")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique()
                        .HasDatabaseName("ix_proveedores_celular")
                        .HasFilter("\"Celular\" != ''");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_proveedores_email")
                        .HasFilter("\"Email\" != ''");

                    b.HasIndex("Razon_Social")
                        .IsUnique()
                        .HasDatabaseName("ix_proveedores_razon_social")
                        .HasFilter("\"RazonSocial\" IS NOT NULL");

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasDatabaseName("ix_proveedores_telefono")
                        .HasFilter("\"Telefono\" != ''");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cajero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("'VTA-' || CAST(\"Id\" AS VARCHAR)", true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Pago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Productos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cajero");

                    b.HasIndex("Cliente");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("Codigo-repetido");

                    b.HasIndex("Estado");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KafeYana.Core.Entities.Entity.RefreshToken", b =>
                {
                    b.HasOne("KafeYana.Core.Entities.Entity.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Detalle_venta", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Venta", "venta")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVenta_Venta");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Ajuste", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Insumo", "InsumoBase")
                        .WithMany("Ajustes")
                        .HasForeignKey("Id_Insumo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Insumo", "InsumoNuevo")
                        .WithMany("AjustesComoNuevo")
                        .HasForeignKey("Id_InsumoNuevo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Opcion", "Opcion")
                        .WithMany("Ajustes")
                        .HasForeignKey("Id_Opcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsumoBase");

                    b.Navigation("InsumoNuevo");

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Comprado", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Producto", "Producto")
                        .WithOne("Comprado")
                        .HasForeignKey("KafeYana.Domain.Entities.Inventario.Comprado", "Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Insumo", "Insumo")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_insumo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Receta", "Receta")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_receta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle_Ronda_Opcion", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Detalle_ronda", "Detalle_Ronda")
                        .WithMany("Opciones")
                        .HasForeignKey("Id_Detalle_Ronda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Opcion", "Opcion")
                        .WithMany()
                        .HasForeignKey("Id_Opcion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Detalle_Ronda");

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle_ronda", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Ronda", "ronda")
                        .WithMany("Detalle")
                        .HasForeignKey("Id_Ronda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Producto", null)
                        .WithMany("Detalle_Rondas")
                        .HasForeignKey("ProductoId");

                    b.Navigation("producto");

                    b.Navigation("ronda");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Elaborado", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Producto", "Producto")
                        .WithOne("Elaborado")
                        .HasForeignKey("KafeYana.Domain.Entities.Inventario.Elaborado", "Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Mesa", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Pedido", "pedido")
                        .WithOne("Mesa")
                        .HasForeignKey("KafeYana.Domain.Entities.Inventario.Mesa", "Id_Pedido")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Opcion", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Variacion", "Variacion")
                        .WithMany("Opciones")
                        .HasForeignKey("Id_variacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variacion");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Producto", b =>
                {
                    b.HasOne("KafeYana.Core.Entities.Inventario.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Categoria_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Promocion", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Producto", "Producto")
                        .WithOne("Promocion")
                        .HasForeignKey("KafeYana.Domain.Entities.Inventario.Promocion", "Producto_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.PromocionDetalle", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KafeYana.Domain.Entities.Inventario.Promocion", "Promocion")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Promocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Receta", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Elaborado", "Elaborado")
                        .WithOne("Receta")
                        .HasForeignKey("KafeYana.Domain.Entities.Inventario.Receta", "Id_Elaborado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Elaborado");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Ronda", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Pedido", "pedido")
                        .WithMany("Rondas")
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Variacion", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Inventario.Elaborado", "Elaborado")
                        .WithMany("Variaciones")
                        .HasForeignKey("Id_Elaborado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elaborado");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("KafeYana.Domain.Entities.Cliente", "Cliente")
                        .WithOne("Pedido")
                        .HasForeignKey("KafeYana.Domain.Entities.Pedido", "Id_Cliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KafeYana.Core.Entities.Entity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KafeYana.Core.Entities.Entity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KafeYana.Core.Entities.Entity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KafeYana.Core.Entities.Entity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KafeYana.Core.Entities.Inventario.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Detalle_ronda", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Elaborado", b =>
                {
                    b.Navigation("Receta");

                    b.Navigation("Variaciones");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Insumo", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("AjustesComoNuevo");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Opcion", b =>
                {
                    b.Navigation("Ajustes");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Producto", b =>
                {
                    b.Navigation("Comprado")
                        .IsRequired();

                    b.Navigation("Detalle_Rondas");

                    b.Navigation("Detalles");

                    b.Navigation("Elaborado")
                        .IsRequired();

                    b.Navigation("Promocion")
                        .IsRequired();
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Promocion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Receta", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Ronda", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Inventario.Variacion", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Mesa");

                    b.Navigation("Rondas");
                });

            modelBuilder.Entity("KafeYana.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
